### ISSUE TITLE
Acoustic training takes longer in the preprocessing and training stages than in the conventional notebook

### ISSUE THREAD

**Issue by naffsan** [MLo7Ghinsan/DiffSinger_colab_notebook_MLo7#16]
Hello! I'm inquiring about a slowdown in the preprocessing and training stages of acoustic training. Unfortunately I'm not familiar with coding, so I couldn't find out where the code was wrong.
Pre-processing with the same data took less than seven minutes no matter how long it took, and now preprocessing takes more than 40 minutes and training takes a long time.
![Capture_diffsinger](https://github.com/MLo7Ghinsan/DiffSinger_colab_notebook_MLo7/assets/98201680/ad055f15-eff2-4de8-bcb9-b91b1b970dce)

**Comment by MLo7Ghinsan** [comment]
the slow down in preprocessing and training solely comes from the options you enabled so check if you used the same features and such with the older versions or not. the older versions doesn't have as much options so there are less process going on compare to the newer version of diffsinger
