### ISSUE TITLE
about change of utils/binarizer_utils.py

### ISSUE THREAD

**Issue by ILG2021** [MLo7Ghinsan/DiffSinger_colab_notebook_MLo7#27]
In the old version, the diffsinger train notebook will change f0_max to 1600, but new version remove it again. Can you tell me why?

**Comment by MLo7Ghinsan** [comment]
Because diffsinger now have f0_max option and the default is set to 1100hz, which is reasonable to RMVPE, and it can be changed manually in the base config if user want it to go higher when using parselmouth or harvest
