### ISSUE TITLE
Missing colon issue

### ISSUE THREAD

**Issue by crlotwhite** [MLo7Ghinsan/DiffSinger_colab_notebook_MLo7#7]
Hello, maintainer. 
I found an issue in your colab notebook.
In the Edit config cell, there is syntax error.
I think you miss a colon in here.

```
#@markdown <font size="-1.5"> Model embeds check; Tension, Energy, Breathiness | for both acoustic and variance
enable_embeds = True #@param {type: "boolean"}
if enable_embeds
  tension_training = True
  energy_training = True
  breathiness_training = True
else:
  tension_training = False
  energy_training = False
  breathiness_training = False
```

![image](https://github.com/MLo7Ghinsan/DiffSinger_colab_notebook_MLo7/assets/76243689/0b30af84-4990-493a-9758-7e2297263358)

**Comment by MLo7Ghinsan** [comment]
Thank you for letting me know! I found that while updating the notebook today lolz
